apiVersion: batch/v1
kind: CronJob
metadata:
  name: posts
  labels:
    app: botan
spec:
  schedule: {{ .Values.posts.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.posts.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
            - name: posts
              image: {{ .Values.image | quote }}
              env:
                - name: PYTHONUNBUFFERED
                  value: "true"
                - name: MONGO
                  valueFrom:
                    secretKeyRef:
                      name: atlas-credentials
                      key: atlas
              command:
                - python
                - ./app/save_posts.py
          restartPolicy: Never
          {{- if (not (empty .Values.imagePullSecrets)) }}
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
            - name: {{ . | quote }}
            {{- end }}
          {{ end }}
      backoffLimit: 1
