apiVersion: batch/v1
kind: CronJob
metadata:
  name: save-posts
  labels:
    app: botan
spec:
  schedule: {{ .Values.schedules.savePosts | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: save-posts
              image: {{ .Values.image | quote }}
              env:
                - name: MONGO
                  valueFrom:
                    secretKeyRef:
                      name: botan
                      key: atlas
              command:
                - python
                - ./app/save_posts.py
          restartPolicy: Never
          {{- if (not (empty .Values.imagePullSecrets)) }}
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
            - name: {{ . | quote }}
            {{- end }}
          {{ end }}
      backoffLimit: 1
